name: Docker Image Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      
    - name: Get next version
      uses: reecetech/version-increment@2023.10.2
      id: version
      with:
        scheme: semver
        increment: patch
        
    - run: git tag ${{ steps.version.outputs.version }}
    - run: git push origin ${{ steps.version.outputs.version }}    
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
   

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: blazordevlab/mailscankit:${{ steps.version.outputs.version }}

    - name: Build and push with latest tag
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: blazordevlab/mailscankit:latest
     
